
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

# Concept and design inspired by:
# Savio Santos



from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\santos.savio\OneDrive - Adventistas\Documentos\Scripts\Projetos\Script Tmelapse obra da faculdade\interface\build\assets\frame0")

status_color = "#FFFF00" # Define a cor para amarelo
status = "Selecione os diretórios" # Define o status inicial

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# Função para atualizar a cor e status de operação
def update_status_color():
    """Atualiza a cor do círculo com base na variável global."""
    global status_color
    global status
    canvas.itemconfig(rectangle, fill=status_color)
    canvas.itemconfig(frase_status, text=status)


# Exemplo de função para alterar a cor e status de operação
def change_color_to_green():
    global status_color
    global status
    status_color = "#00FF00"  # Define a cor para verde
    status = "Pronto para executar"
    update_status_color()

def change_color_to_red():
    global status_color
    global status
    status_color = "#FF0000"  # Define a cor para vermelho
    status = "Executando, não interromper..."
    update_status_color()

def change_color_to_yellow():
    global status_color
    global status
    status_color = "#FFFF00"  # Define a cor para amarelo
    status = "Selecione os diretórios"
    update_status_color()


window = Tk()

window.geometry("700x500")
window.configure(bg = "#FFFFFF")

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

# Título
canvas.place(x = 0, y = 0)
canvas.create_text(
    302.0,
    8.0,
    anchor="nw",
    text="AutoMove 1.0",
    fill="#000000",
    font=("Inter", 12 * -1)
)

# Sinal do status
rectangle = canvas.create_rectangle(
    10.0,
    478.0,
    22.0,
    490.0,
    fill=status_color,
    outline="")

frase_status = canvas.create_text(
    32.0,
    478.0,
    anchor="nw",
    text="Status: Selecione os diretórios",
    fill="#000000",
    font=("Inter", 12 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    # command=lambda: print("Clicado: Selecionar diretório inicial"),
    command= change_color_to_green(),
    relief="flat"
)
button_1.place(
    x=100.0,
    y=246.0,
    width=174.0,
    height=26.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    # command=lambda: print("Clicado: Selecionar diretório de saída"),
    command= change_color_to_red(),
    relief="flat"
)
button_2.place(
    x=100.0,
    y=323.0,
    width=184.0,
    height=26.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Clicado: Porque usar"),
    relief="flat"
)
button_3.place(
    x=373.0,
    y=78.0,
    width=101.0,
    height=26.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Clicado: Qual é o padrão"),
    relief="flat"
)
button_4.place(
    x=369.0,
    y=165.0,
    width=109.0,
    height=26.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    # command=lambda: print("button_5 clicked"),
    command= change_color_to_yellow,
    relief="flat"
)
button_5.place(
    x=245.0,
    y=393.0,
    width=209.0,
    height=52.0
)

canvas.create_text(
    295.0,
    252.0,
    anchor="nw",
    text="Nenhum diretório selecionado",
    fill="#818181",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    295.0,
    329.0,
    anchor="nw",
    text="Nenhum diretório selecionado",
    fill="#818181",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    60.0,
    64.0,
    anchor="nw",
    text="Esta ferramenta tem o propósito de \n"
    "facilitar a organização dos arquivos de \n"
    "imagem gerados para Timelapse pela \n"
    "câmera Intebras VIP.",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    60.0,
    157.0,
    anchor="nw",
    text="O script move as imagens contidas nas\n"
    "pastas e subpastas que correspondem ao\n"
    "padrão e renomeia com a data do registro.",
    fill="#000000",
    font=("Inter", 14 * -1)
)

window.resizable(False, False)
window.mainloop()
