name: Ola, Mundo!

on: [push]

jobs:
  ola_mundo_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

    steps:
      - name: Ola, Mundo!
        run: echo "Ola, Mundo!"

      - name: Exemplo de Ação
        run: echo "Esta é uma ação de exemplo."